model:
  init_channels: 8
  bottleneck_channels: 32

data:
  root_dir: "binary_maps_dataset"
  mask_ratio: 0.9

training:
  num_epochs: 100
  batch_size: 256
  num_workers: 4
  device: "cuda"
  assets_dir: "assets"
  checkpoints_dir: "checkpoints"
  gradient_clip: true
  gradient_clip_value: 1.0
  mask_ratio: 0.9

optimizer:
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0.0001

scheduler:
  cosine_t_max: 20
  eta_min: 1e-6
  plateau_factor: 0.5
  plateau_patience: 5
  min_lr: 1e-7

loss:
  name: "BCELoss"