motion_planning_config:
  map_generation_config:
    model_checkpoint_path: "sampling_based_planning_framework/checkpoints/best_model.pth"
    model_config_path: "/sampling_based_planning_framework/config/prediction_config.yaml"
    device: "cuda:0"
    operation_limits: [400, 400, 20]
  perception_config:
    workspace_bounds: [[0.30, 0.05], [0.85, 0.6]]
    grid_resolution: 100
    contact_threshold: 0.005
    min_object_points: 10
    body_link: [11]
  motion_planning_config:
    operation_limits: {}
    position_K: [100.0, 100.0]
  simulation_test_config:
    results_dir: "/assets/"
    num_tests: 100
    robot_urdf_path: "single_arm/left_arm.urdf"
    obstacle_count: 3
    min_obstacle_distance: 0.1